### ISSUE TITLE
How to set a syntax error callback without global variables?

### ISSUE THREAD

**Issue by Phytolizer** [jplevyak/dparser#32]
The declaration of D_SyntaxErrorFn is simple:
```c
typedef void (*D_SyntaxErrorFn)(struct D_Parser *);
```
However, as far as I see, I can't pass in any of my own data (in my case, a logger). Is there a way to do that without globals?

**Comment by jplevyak** [comment]
When you create the struct D_Parser object with the function new_D_Parser it creates an extended object with more storage (struct Parser).    You can add fields to struct D_Parser or struct Parser or realloc with additonal storage and cast (D_Parser*p) to your struct (struct MyData*)((char*)p + sizeof(Parser)).   I can add a 'struct D_Parser_User *user_data' to struct D_Parser if you want to use the unmodified distribution then you can set it to your own struct during parser initialization.

**Comment by Phytolizer** [comment]
That would be great, thank you! For now I'll do it myself, but having it in the original source would be neat!

**Comment by jplevyak** [comment]
Done in version 1.34
